version: 2
aliases:
  build_config: &build_config
    environment:
       BASH_ENV: ~/.bashrc

    steps:
      - checkout

      # Versions Check
      - run:
          name: Node version
          command: node -v

      - run:
          name: EMCC version
          command: emcc --version

      - run:
          name: Install Yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash

      - run:
          name: Yarn version
          command: yarn --version

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install base packages
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          type: shell
          name: Test Emscripten-CLI and Install SDK
          command: cd emscripten && source ./test_emcc.sh

      - run:
          name: Lint and Test packages
          command: yarn test

jobs:
  build:
    docker:
      - image: trzeci/emscripten:sdk-tag-1.38.32-64bit
    <<: *build_config
